name: debug

on: [push]

jobs:
  debug_busybox:
    runs-on: ubuntu-latest
    name: Debug busybox
    strategy:
      fail-fast: false
      matrix:
        id:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
    steps:
    - name: Deps
      run: |
        sudo apt-get update
        sudo apt-get install -y cpuid
    - name: Print CPU
      run: |
        echo "--------------------------------------------------------------------------------"
        echo "/proc/cpuinfo"
        echo "--------------------------------------------------------------------------------"
        cat /proc/cpuinfo

        echo "--------------------------------------------------------------------------------"
        echo "cpuid"
        echo "--------------------------------------------------------------------------------"
        cpuid
    - name: Busybox 1.35
      run: |
        docker run -t --rm busybox:1.35 sha256sum /etc/passwd
    - name: Busybox latest
      run: |
        ulimit -c unlimited
        echo '/tmp/core.%h.%e.%t' | sudo tee /proc/sys/kernel/core_pattern

        mkdir out
        docker run -t --rm -v $PWD/out:/out busybox cp /bin/busybox /out
        
        cp out/busybox out/sha256sum
        sudo ./out/sha256sum ./out/sha256sum || true
        sudo ls -lh /tmp/
        sudo xxd /tmp/core*
